docker: update quickstart script to use docker compose v2.
Update the `bin/danbooru` quickstart script to install and use Docker Compose v2 instead of v1.

https://docs.docker.com/compose/migrate/

diff --git a/bin/danbooru b/bin/danbooru
--- a/bin/danbooru
+++ b/bin/danbooru
@@ -11,7 +11,7 @@
 #
 # Alternatively, if you already have Docker installed, you can just do:
 #
-#     docker-compose up
+#     docker compose up
 #
 # This script is just a wrapper for that command.
 
@@ -24,22 +24,33 @@ has() {
 
 # Install Docker and Docker Compose if they're not installed already.
 install_docker_compose() {
-  if has docker && has docker-compose; then
+  if has docker && docker compose > /dev/null 2>&1; then
     return
   fi
 
   # Debian and Ubuntu
   if has apt-get; then
-    sudo apt-get update
-    sudo apt-get install -y docker.io docker-compose
+    if ! has curl; then
+      sudo apt-get update
+      sudo apt-get install -y curl
+    fi
+
+    curl -fsSL https://get.docker.com | sh
+
   # Fedora
   elif has dnf; then
-    sudo dnf install -y docker docker-compose
+    if ! has curl; then
+      sudo dnf install -y curl
+    fi
+
+    curl -fsSL https://get.docker.com | sh
+
   # Arch Linux
   elif has pacman; then
     sudo pacman -Sy --noconfirm docker docker-compose
+
   else
-    echo "Error: Couldn't automatically install docker-compose. Install docker-compose manually."
+    echo "Error: Couldn't install Docker automatically. See https://docs.docker.com/engine/install/ for how to install Docker manually."
     exit 1
   fi
 }
@@ -53,4 +64,4 @@ start_docker() {
 
 install_docker_compose
 start_docker
-sudo docker-compose "${@:-up}"
+sudo docker compose "${@:-up}"
