docker: redo docker install script.
Rename the install script from `bin/danbooru` to `bin/setup` and have it automatically create the
`.env.local` and `config/danbooru_local_config.rb` files.

The new procedure for running a local Danbooru instance is:

    bin/setup
    docker compose up

or:

    curl -sSL https://raw.githubusercontent.com/danbooru/danbooru/master/bin/setup | sh

Fixes #5627 (Error response from daemon: invalid mount config ... .danbooru_local_config.rb does not
exist). There's no easy way to pass config files in to Docker without having it error out if they
don't exist. So the new setup procedure is just to run `bin/setup` to create these files before
running `docker compose up`.

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,33 +1,130 @@
-#!/usr/bin/env ruby
-require "fileutils"
+#!/bin/sh
+#
+# This script sets up everything need to run Danbooru under Docker. It installs Docker and Git (if
+# they're not already installed), downloads the Danbooru code from Github (if it's not already
+# downloaded), and initializes the config files.
+#
+# If this script is run with `curl -sSL https://raw.githubusercontent.com/danbooru/danbooru/master/bin/setup | sh`,
+# then it will automatically run `docker compose up` to start Danbooru. Otherwise you can run `docker compose up`
+# manually to start Danbooru.
 
-# path to your application root.
-APP_ROOT = File.expand_path("..", __dir__)
+# Usage:
+#
+#  $ bin/setup
+#  $ sudo docker compose up
 
-def system!(*args)
-  system(*args, exception: true)
-end
+set -eu
 
-FileUtils.chdir APP_ROOT do
-  # This script is a way to set up or update your development environment automatically.
-  # This script is idempotent, so that you can run it at any time and get an expectable outcome.
-  # Add necessary setup steps to this file.
+DANBOORU_REPO=https://github.com/danbooru/danbooru
 
-  puts "== Installing dependencies =="
-  system! "gem install bundler --conservative"
-  system("bundle check") || system!("bundle install")
+# Check if program exists.
+has() {
+  type "$1" > /dev/null 2>&1
+}
 
-  # puts "\n== Copying sample files =="
-  # unless File.exist?("config/database.yml")
-  #   FileUtils.cp "config/database.yml.sample", "config/database.yml"
-  # end
+# Ask for confirmation before proceeding.
+confirm() {
+  read -p "$1 (y/n) " REPLY
+  [ $REPLY = "y" ]
+}
 
-  puts "\n== Preparing database =="
-  system! "bin/rails db:prepare"
+# Clone the Danbooru repo and cd into it, unless we're already in it.
+clone_repo() {
+  if grep -s danbooru .git/config > /dev/null; then
+    return
+  fi
 
-  puts "\n== Removing old logs and tempfiles =="
-  system! "bin/rails log:clear tmp:clear"
+  install_git
+  git clone "$DANBOORU_REPO"
+  cd danbooru
+}
 
-  puts "\n== Restarting application server =="
-  system! "bin/rails restart"
-end
+# Install Git if it's not installed already.
+install_git() {
+  if has git; then
+    return
+  elif ! confirm "Git not found. Install it?"; then
+    echo "You must install Git to proceed. See https://git-scm.com/downloads to install it manually."
+    exit 1
+  fi
+
+  if has apt-get; then
+    sudo apt-get update
+    sudo apt-get install -y git
+  elif has dnf; then
+    sudo dnf install -y git
+  elif has pacman; then
+    sudo pacman -Sy --noconfirm git
+  else
+    echo "Error: Couldn't install Git. See https://git-scm.com/downloads to install Git manually."
+    exit 1
+  fi
+}
+
+# Install Docker and Docker Compose if they're not installed already.
+install_docker_compose() {
+  if has docker && docker compose > /dev/null 2>&1; then
+    return
+  elif ! confirm "Docker not found. Install it?"; then
+    echo "Error: You must install Docker and Docker Compose to proceed. See https://docs.docker.com/engine/install/ to install it manually."
+    exit 1
+  fi
+
+  # Debian and Ubuntu
+  if has apt-get; then
+    if ! has curl; then
+      sudo apt-get update
+      sudo apt-get install -y curl
+    fi
+
+    curl -fsSL https://get.docker.com | sh
+
+  # Fedora
+  elif has dnf; then
+    if ! has curl; then
+      sudo dnf install -y curl
+    fi
+
+    curl -fsSL https://get.docker.com | sh
+
+  # Arch Linux
+  elif has pacman; then
+    sudo pacman -Sy --noconfirm docker docker-compose
+
+  else
+    echo "Error: Couldn't install Docker automatically. See https://docs.docker.com/engine/install/ to install Docker manually."
+    exit 1
+  fi
+
+  # Start Docker if it's not running already.
+  if has systemctl; then
+    sudo systemctl start docker
+  fi
+}
+
+# `docker compose up` needs these files to exist.
+initialize_config_files() {
+  touch -a .env.local config/danbooru_local_config.rb
+}
+
+# Start Danbooru if running this script with `curl | sh`.
+start_danbooru() {
+  if [ "$0" != "sh" ]; then
+    return
+  fi
+
+  # Test whether we need sudo to run docker.
+  if docker version > /dev/null 2>&1; then
+    docker compose "${@:-up}"
+  elif sudo docker version > /dev/null 2>&1; then
+    sudo docker compose "${@:-up}"
+  else
+    echo "Error: Couldn't run Docker. Make sure Docker is installed correctly."
+    exit 1
+  fi
+}
+
+install_docker_compose
+clone_repo
+initialize_config_files
+start_danbooru
